### ISSUE TITLE
Plan to release a lightmotif-io Python package?

### ISSUE THREAD

**Issue by Ebedthan** [althonos/lightmotif#6]
Hi @althonos,

Do you have any plans to release lightmotif-io as a Python package?

Thanks for letting me know.

**Comment by althonos** [comment]
Hi Anicet, I'll try to add support for that eventually as a function of the `lightmotif` Python package; the one thing I need to figure out is the dynamic detection of the alphabet, which is slightly annoying given how I handle alphabets internally.

**Comment by althonos** [comment]
I added the `lightmotif.load` function in `v0.9.0` which lets you load matrices stored in JASPAR, TRANSFAC or UNIPROBE format from a path or a file-like object.

**Comment by Ebedthan** [comment]
Hi @althonos,
Amazing works as always!
Will test soon.
Thanks!
